# Caching the inverse of a matrix
# Includes the functions makeCacheMatrix and cacheSolve
# makeCacheMatrix takes 2D matrix and prepares list of get/set functions for the original matrix and
# its inverse.
# cacheSolve takes the matrix generated by makeCacheMatrix and either
# - calculates the inverse of the original matrix
# - or retrieves the inverse matrix already in cache

# Example with 2x2 matrix proposed by mentor Alan E Berger 
# > n1 <- matrix(c(6,2,8,4), nrow = 2, ncol = 2) 
# n1
# [,1] [,2]
# [1,]    6    8
# [2,]    2    4
# > m<- makeCacheMatrix(n1)
# Calculate the inverse matrix first
# cacheSolve(m)
# [,1]  [,2]
# [1,]  0.50 -1.00
# [2,] -0.25  0.75
# Retrieve it if it's being calculated before
# > cacheSolve(m)
# getting cached inverse matrix
# [,1]  [,2]
# [1,]  0.50 -1.00
# [2,] -0.25  0.75

# Example with 3x3 matrix
# > n1<- matrix(c(0,1,1,1,0,1,1,1,0),nrow=3,ncol=3)
# > n1
# [,1] [,2] [,3]
# [1,]    0    1    1
# [2,]    1    0    1
# [3,]    1    1    0
# > solve(n1)
# [,1] [,2] [,3]
# [1,] -0.5  0.5  0.5
# [2,]  0.5 -0.5  0.5
# [3,]  0.5  0.5 -0.5
# > m<- makeCacheMatrix(n1)
# > cacheSolve(m)
# [,1] [,2] [,3]
# [1,] -0.5  0.5  0.5
# [2,]  0.5 -0.5  0.5
# [3,]  0.5  0.5 -0.5
# > cacheSolve(m)
# getting cached inverse matrix
# [,1] [,2] [,3]
# [1,] -0.5  0.5  0.5
# [2,]  0.5 -0.5  0.5
# [3,]  0.5  0.5 -0.5

makeCacheMatrix <- function(x = matrix()) {
  # Input: invertable 2D matrix
  # Output: list of functions to get/set input matrix and get/set inverse matrix
  inv_output<- NULL
  
  set <- function(y) {
    x <<- y
    inv_output <<- NULL
  }
  get <- function() x
  
  setinv <- function(inverse) inv_output <<-inverse
  getinv <- function() inv_output
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}


cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  # This function computes the inverse of the special "matrix" returned by makeCacheMatrix above. 
  # If the inverse has already been calculated (and the matrix has not changed), then
  # cacheSolve should retrieve the inverse from the cache
  
    inv_output <- x$getinv()
    if(!is.null(inv_output)) {
      message("getting cached inverse matrix")
      return(inv_output)
    }
    data <- x$get()
    inv_output <- solve(data, ...)
    x$setinv(inv_output)
    inv_output
}
